name: Build

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  check:
    name: check
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install meson ninja-build
      - name: Configure
        run: meson setup _build
      - name: Build
        run: meson compile -C _build
